### ISSUE TITLE
Tautulli Remote iOS connection issue

### ISSUE THREAD

**Issue by peppoonline** [zSeriesGuy/Tautulli#10]
Hey mate,

I know that's most likely not your problem, but perhaps you can give me a hint where to look after the problem :)
Tautulli Remote for Android works perfectly fine with your Version of Tautulli.
But I get a connection error via the iOS version:
TautulliRemoteCore.ServerError- Error 0
Couldn't establish the connection to Tautulli.

Besides appearantly the iOS version sucks - what to do? :)

Regards and thanks for all your work!
Dominik

**Comment by zSeriesGuy** [comment]
I haven't done any testing with the Tautulli Remote app. So I don't really know what the issue might be.
If I had to guess, I would guess that perhaps it is calling a method in the webserve.py module that I might have removed after thinking it was dead code not realizing that the code may be used for external callers.
When I get time, I'll compare the methods in webserve.py in the official version to mine and see what I removed.
If you have time and wouldn't mind doing that, I would appreciate it.

**Comment by peppoonline** [comment]
Hey mate, I tried to compare, but since I am no coder, that's really nothing I can qualify :)

**Comment by zSeriesGuy** [comment]
No worries. I'll get around to it eventually. Just been busy on another project for awhile.

**Comment by luisvillalobos528** [comment]
Any news on this issue? I just discovered this fork and loving it but having that same error on IOS app

**Comment by zSeriesGuy** [comment]
@luisvillalobos528 When you get the error, are there any messages in the Tautulli log? Unfortunately at this time, I don't have an Apple device to test with.

**Comment by zSeriesGuy** [comment]
I don't have an Apple device to test this with. But I pushed some changes to the master branch that may fix the issue.
Since those Tautulli remote apps don't handle multi-server, I made a change to force selection of the first defined server. The Activity page will still show activity for all servers, but the thumbnail won't be right unless the activity is on the first server.
The Libraries list will only be for the first server.

Please try out this update and let me know if it resolves the IOS app issue.

**Comment by luisvillalobos528** [comment]
Same error I think, but I can't see if I pull the latest update the version that says on settings is VERSION V4.0.07
Here's the logs on server side, because on the iOS theres no way to see them:
[tautulli.log](https://github.com/zSeriesGuy/Tautulli/files/4017069/tautulli.log)
[tautulli_api.log](https://github.com/zSeriesGuy/Tautulli/files/4017071/tautulli_api.log)

**Comment by zSeriesGuy** [comment]
From your api log, it appears you don't have the new code. I did not update the version info. 
From the Settings gear in the upper right, run the Check for Updates and if it identifies updates, do the update.

Once it is updated, you should be able to run this command from a browser and get a json response.
You can get your apikey from the settings-web interface page down at the bottom.
Try it before and after doing the code update.

http://your-url:your-port/api/v2?apikey=put-your-apikey-here&cmd=get_server_identity

**Comment by luisvillalobos528** [comment]
Ok so like the update didn't want to take so I deleted the whole thing and reinstalled, and the iOS app works like you said it only shows library info for 1 out of the 2 servers (its ok), but when both players are streaming it shows clients from both server and their info, the only thing is that there is a doble exclamation mark on the iOS app in the more tab with a server not reachable even tough we know it works, i will attach the log for your info but this is enough for me Thanks so much and let me know if you need any more info 

[tautulli_api.log](https://github.com/zSeriesGuy/Tautulli/files/4018075/tautulli_api.log)

**Comment by zSeriesGuy** [comment]
Cool. We're making headway.
I just pushed a couple more changes that should resolve that.
Please give it a try again.
Your api log has been very helpful. After you have tried it again, please review that log and see if you have any more failed function calls.
Thanks a bunch.

In order for the remote Tautulli apps to fully support this code, those apps would need some changes. I can't make those changes and I highly doubt they will make the changes in support of this unofficial fork. I am going to work on the responsiveness of the interface to make the web browser interface more usable on mobile devices at some point.

**Comment by zSeriesGuy** [comment]
@luisvillalobos528 Were you able to test the updated code? Are the double exclamation marks gone now?

**Comment by zSeriesGuy** [comment]
I will assume this issue is resolved and will commit this change.
