### ISSUE TITLE
Tables (Users, Historys, Graphs,...) will not be updated anymore

### ISSUE THREAD

**Issue by prinzpi** [zSeriesGuy/Tautulli#11]
Hi, 
I'm facing a quite strange issue since a week (between 22nd and 23rd April the issue has occurred):
All tables, graphs, the history won't be updated anymore (just like that everything after 22nd / 23rd April will be ignored), but there are still plays and the active plays will also shown on the Tautulli main page. 

This is the most significant log entry (maybe this is the reason?!): 
```
2019-05-22 08:52:40 - ERROR   :: WebSocket-Plex-Entertainment 2 : Uncaught exception: Traceback (most recent call last):
  File "/opt/Tautulli/plexpy/logger.py", line 341, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Tautulli/plexpy/web_socket.py", line 161, in connect
    logger.error(u"Tautulli WebSocket :: %s: %s." % (self.server.CONFIG.PMS_NAME, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)

2019-05-22 08:52:44 - ERROR   :: WebSocket-Plex-Entertainment : Uncaught exception: Traceback (most recent call last):
  File "/opt/Tautulli/plexpy/logger.py", line 341, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/Tautulli/plexpy/web_socket.py", line 161, in connect
    logger.error(u"Tautulli WebSocket :: %s: %s." % (self.server.CONFIG.PMS_NAME, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128
```

**Version:**
Tautulli: 3.0.00
PMS: 1.15.6.1079 

**Branch:**
V3.0.00

**Operating system:**
1. Server: Ubuntu 16.04.6 LTS
2. Server: Ubuntu 18.04.2 LTS

**Python version:**
3.5.2

**Link to logs:**
[tautulli (1).log](https://github.com/zSeriesGuy/Tautulli/files/3241073/tautulli.1.log)

**Comment by zSeriesGuy** [comment]
@prinzpi Is there some kind of special character in your plex server name?

**Comment by prinzpi** [comment]
> @prinzpi Is there some kind of special character in your plex server name?

Yes, the server are named like this:
Plex-Entertainment
Plex-Entertainment2 

Do you think the "-" character is may causing this issue? But why since a week and not before?!
I'm using your version now longer than a month and at the beginning there wasn't a issue like that.

**Comment by zSeriesGuy** [comment]
@prinzpi 
Never mind. There is nothing wrong with your server names and I can see from your log that it was working fine.
I'm still looking thru the log and haven't seen anything yet except this:
Tautulli Notifiers :: Failed to run script: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/opt/Tautulli/custom_scripts'

That would not cause problems with the logging. But I just wanted to point that out.

**Comment by prinzpi** [comment]
@zSeriesGuy Thanks for the hint, need to delete this unused custom script.

If you need anything else to may solve this issue feel free to ask.
Otherwise I would just do a backup and then re-install it - hopefully that this will fix the issue.

**Comment by zSeriesGuy** [comment]
@prinzpi I am guessing at this point that due to the error that you listed with the websocket module, that the websocket listener crashed and is not longer listening to events from the plex server.
Try restarting tautulli and then play something and let's see if it gets logged.
If that does resolve it, I'll see if I can figure out why you got that error.

**Comment by prinzpi** [comment]
@zSeriesGuy After the restart it's now working again. 
I could have thought it myself just to try an restart haha.
Thank you.

**Comment by zSeriesGuy** [comment]
@prinzpi 
Do you have a movie that has a special character in the name. Maybe an umlaut?

**Comment by zSeriesGuy** [comment]
@prinzpi 
I see the problem. I will fix the code.

**Comment by zSeriesGuy** [comment]
@prinzpi 
I pushed a change to the V3.0.00 branch. You might want to download those changes.

**Comment by prinzpi** [comment]
@zSeriesGuy thanks, I'll update asap. Regards and keep up the great work.
