### ISSUE TITLE
Have to Flush Temporary Sessions

### ISSUE THREAD

**Issue by Craig-H** [zSeriesGuy/Tautulli#13]
In history, newly watched items show with the stopped icon in the left most column. This has to be tidied by using Flush Temporary Sessions.

**Comment by zSeriesGuy** [comment]
@Craig-H
Thank you for reporting this.
I'm trying to recreate it and am not seeing it.
I do see where when a stream buffers, the buffering icon stays even when it is no longer buffering.
Could you give me more detail? When you say newly watched, do you mean the movie is completed?
Can you give me a screen shot?

**Comment by zSeriesGuy** [comment]
I think this may be fixed in the V4.0.00 branch and may be related to the XML parsing issue.
