### ISSUE TITLE
Newsletter Image Issue

### ISSUE THREAD

**Issue by pellett655** [zSeriesGuy/Tautulli#20]
Getting the following error when using Cloudinary as my Newsletter Image Hosting provider.  Using Version : V4.0.0.01

Error: 	Tautulli Helpers :: Unable to upload image 'name of movie here' (art) to Cloudinary: a bytes-like object is required, not 'str'

I'm guessing this is a Python 3 issue ?

**Comment by zSeriesGuy** [comment]
Thank you for catching this. I have updated the code to fix it. Please let me know if this update resolves it for you.
And let me know if you find any other issues. :)

**Comment by zSeriesGuy** [comment]
@pellett655  Did the update fix your issue?

**Comment by pellett655** [comment]
Yes it did!  Thanks so much!
