### ISSUE TITLE
Newsletter Notification Failing

### ISSUE THREAD

**Issue by pellett655** [zSeriesGuy/Tautulli#21]
[Tautulli_Log.txt](https://github.com/zSeriesGuy/Tautulli/files/3912451/Tautulli_Log.txt)

I'm getting the attached error when trying to preview a recently added notification.  This only happens on TV shows which is strange.

Tautulli Version:  v4.0.05
Python 3.8

**Comment by zSeriesGuy** [comment]
@pellett655 I just pushed a code change that I think should fix this. Please let me know if this resolves the issue.
Thanks for reporting this issue.

**Comment by pellett655** [comment]
Upgraded to v4.0.06 and still am getting this error when generating the newsletter.
[40006_newsletter_error.txt](https://github.com/zSeriesGuy/Tautulli/files/3917165/40006_newsletter_error.txt)

**Comment by zSeriesGuy** [comment]
With this error, I was able to identify issues with both TV Shows and Music in the newsletter generation process. Should be fixed now. 
I just pushed V4.0.07.
Let me know how it goes.
And thanks again.

**Comment by pellett655** [comment]
@zSeriesGuy Yep, fixed newsletters for me!  Thanks again!

**Comment by zSeriesGuy** [comment]
Great.
