### ISSUE TITLE
Using rclone Feature

### ISSUE THREAD

**Issue by isnoch** [zSeriesGuy/Tautulli#22]
Can you please give more Information (an example) about the rclone "watch" Feature on your MultiServer Tautulli?

-My rclone Settings are: Mounted at /volume1/data/rclone_mnt
-rclone rc features is enabled
-on Tautulli Mount-Directory is /volume1/data/rclone_mnt
-and the Temp folder also /volume1/data/rclone_mnt
-and the tempfile is rclone_mount_test.txt

But Tautulli says "Monitor test failed"
in the Rclone debug file i read "ERROR : rc: "operations/copyfile": error: object not found", but i cant found the path tautulli now copy the tempfile.

Thanks a lot

**Comment by isnoch** [comment]
oh, i found the Way!

-**Mount Directory** is the absolute Path /volume1/data/rclone_mnt
-**Temp Directory** is the relative Path from Mount Directory above (also in my case "temp" without "/")
-**Test Filename** is a File in Mount Directory, it must be create from Hand and saved inside the Mount Directory

**Comment by zSeriesGuy** [comment]
Glad you found it.
Temp Directory is any directory to temporarily copy the test file to. And the test file can be any file. I created by hand a small txt file with one line in it....testfile.txt.
I use /dev/shm.
The rclone monitoring copies the testfile from the mount directory to the temp directory at regular intervals (I don't recall the interval) to verify that rclone is functioning. After the copy, it deletes the test file from the temp directory.
