### ISSUE TITLE
You are running an unknown version of Tautulli. Update or Dismiss

### ISSUE THREAD

**Issue by isnoch** [zSeriesGuy/Tautulli#23]
When i enable the Update checkbox, it shows the Popup: "You are running an unknown version of Tautulli. Update or Dismiss".

**Version:** V4.0.07 
**Operating system:** Linux
**Python version:** newest

**Link to logs:** no Error in Tautulli Log

**Comment by zSeriesGuy** [comment]
How did you install the code?
Did you download and unzip it? Or did you git clone it?
As I recall, if you download and unzip it, it does not build the git environment and then does not know what the version is.

Did you upgrade a previous Tautulli? Or is this a new install?
In your config.ini, is git_user = zSeriesGuy? This setting is so that it looks at my repo and not the official repo.

**Comment by zSeriesGuy** [comment]
This could also be that I have committed a change to the master branch and did not yet update the Release tag. I'll try to get that done today.

**Comment by isnoch** [comment]
My Setup is a fresh unzip & install, but without git. That will be the Problem that you say.
If there an workaround to update (in tautulli) without install the git?

**Comment by zSeriesGuy** [comment]
It should work running the the update. The update will essentially turn the download/unzip into a git install if you have git installed. To ensure git is installed, you can run 
sudo apt-get install git-core

**Comment by isnoch** [comment]
Now with git and git_user = zSeriesGuy in config.ini it works, thanks a lot for your hard work

**Comment by ksurl** [comment]
@zSeriesGuy I don't see changing the git_user setting anywhere in the install instructions. my install kept crashing when it checked for updates from the original repo. could you include this in the wiki install page?

**Comment by zSeriesGuy** [comment]
@ksurl Thank you for pointing this out.
 I think I had made changes in my code to change the git_user during an update. But there may be a timing issue there if the update is being attempted while it has not yet been changed. 
I added a note in the wiki installation per your suggestion.

**Comment by ksurl** [comment]
Maybe it was because I migrated from an existing python2 based Tautulli install. Probably wouldn't happen on a clean install.
