### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by edrock200** [zSeriesGuy/Tautulli#25]
Hey zseriesguy! Thanks for all the hard work on this. The plexguide community is interested in making this a docker container. I don't know if you had any plans to. If not, I'm not sure how the rules work on using your code to embed in a docker container if I were to try to figure it out myself. Figured I should make sure it's kosher first. Thanks again!

**Comment by zSeriesGuy** [comment]
That would be cool with me.
I have no docker plans because I know nothing about docker. :)
Go for it.

**Comment by edrock200** [comment]
Thank you! I'll try my best, I figure it's the best way to learn. And thanks for this awesome project, it's my only tautulli instance now!

**Comment by zSeriesGuy** [comment]
Yep. That is the best way to learn. Working on this multi-server version of Tautulli is how I learned Python. Unfortunately, I didn't understand the small-commit concept in github. So this code will never get incorporated into the original.

**Comment by edrock200** [comment]
Well I appreciate the efforts. Got the container working by forking the tautulli container, debasing it on Ubuntu and python3.8. Still needs some tweaking but it's working so far! 

https://github.com/edrock200/Tautulli-Docker/
