### ISSUE TITLE
Tautulli won't see plex servers with custom SSL cert/name published

### ISSUE THREAD

**Issue by edrock200** [zSeriesGuy/Tautulli#26]
**Version:**
Latest version on git as of 2/18/2020
**Branch:**
Master
**Commit hash:**

**Operating system:**
Windows & Ubuntu 18.04
**Python version:**
3.8
**What you did?**
Tried to add a plex server with custom SSL cert
**What happened?**
The servers don't even show up as options, as though they are not part of my account, however 3 other servers without custom SSL certs show up fine
**What you expected?**
The servers to show up correctly
**How can we reproduce your issue?**
Create a "LetsEncrypt" custom cert for your plex server
Redirect port 443 to 32400 on the server
In plex settings under network, apply your cert and set it to publish a custom dns name to plex.tv as https://your.fqdn.name:443

**What are your (relevant) settings?**
Not sure what other settings to note here
**Link to logs:**
I can provide, but in the discovery it litterally doesn't even pull back those server names so they are nowhere to be found in the logs. It's almost as if it won't do anything outside of the plex universal subdomain names.

**Comment by zSeriesGuy** [comment]
I will have to recreate this on my server and debug to see what's going on. I'm sure it has something to do with the auto-discovery of servers from your plex account.

**Comment by zSeriesGuy** [comment]
I just attempted to recreate this but without the port redirecting and it all worked fine.
Does it work if you remove the ":443" from the custom DNS name and just specify your.fqdn.name?
I only specified my fqdn in the Custom certificate Domain field in the Plex network settings without the https:// and without the port.

**Comment by edrock200** [comment]
I will give that a shot and report back, thank you! I added it because the default entry had :32400 and I wanted to ensure it was publishing 443 vs 32400. But I'll test it out.

**Comment by zSeriesGuy** [comment]
Have you tested yet? Is this resolved?
