### ISSUE TITLE
Installation Guide Needs Editing (?)

### ISSUE THREAD

**Issue by MrGarrettSmith** [zSeriesGuy/Tautulli#28]
**Version:**
Latest version on git as of 3/23/2020

**Branch:**
Master

**Commit hash:**

**Operating system:**
Windows 10
**Python version:**
3.8 (latest)
**What you did?**
Struggled to follow installation guide
**What happened?**
Had to make small edits to install this fork of Tautulli
**What you expected?**
To not have to
**How can we reproduce your issue?**
Follow the guide and try to install this fork of Tautulli
**What are your (relevant) settings?**
Not sure what other settings to note here
**Link to logs:**
[No need, the Windows 10 installation guide just needs to be edited / updated.](https://github.com/zSeriesGuy/Tautulli/wiki/Installation)

_For me, changing "python3" to "python" worked:_
>   Go to https://gitforwindows.org/ and download git.
>     Run the installer, select all the defaults except for the section called "Adjusting your PATH environment" - here select "Git from the command line and also from 3rd-party software".
>     Complete the rest of the installation with the default options.
>     Right click on your desktop and select "Git Gui".
>     Select "Clone Existing Repository".
>     In the "Source Location" enter: https://github.com/zSeriesGuy/Tautulli.git
>     In the "Target Directory" enter a new folder where you want to install Tautulli to (e.g. C:\Tautulli).
>     Click "Clone".
>     When it's finished a Git Gui windows will appear, just close this Window.
>     Open a command window.
>     CD to where you cloned the Tautulli repository (e.g. cd C:\Tautulli).
>     **Type: python** -m venv .\
>     Type: .\scripts\activate
>     **Type: python** -m pip install --upgrade pip setuptools pip-tools
>     Type: pip3 install -r requirements.txt
>     **Type: .\scripts\python** Tautulli.py to start Tautulli

**Other notes & a related issue:**
I am not incredibly saavy, with Python or this process, but I felt the need to bring it to your attention. Perhaps I made an error. My other main concern was actually [attempting to run as a daemon.
](https://github.com/Tautulli/Tautulli-Wiki/wiki/Install-as-a-daemon#linux-systemd) Although you specify: 
> Be sure that the start command in your daemon process executes \scripts\python3 in the folder where you extracted the ZIP file (eg. C:\Tautulli\scripts\python3).

I'm not sure if this is still accurate since I had to change "python3" to "python." I was unable to get Tautulli to run "non-interactively" with that added to the "Tautulli.cmd." I don't know another way to ask for help other than here. My Python installation is "C:\Python38" so when I tried:
`Start C:\Python38\pythonw.exe C:\Tautulli\Tautulli.py`
or
`Start C:\Python38\pythonw.exe C:\Tautulli\scripts\python3`
or
`Start C:\Python38\pythonw.exe C:\Tautulli\scripts\python`

I was not able to get Tautulli to run (at startup).
Through the "Interactive" method, yes. Non-Interactive, no.

Any help on this is greatly appreciated. Thank you! :)

**Comment by zSeriesGuy** [comment]
Hi. I'm no python expert either. :)

To start Tautulli using pythonw, execute the pythonw from the scripts folder of your VENV.
Something like:
C:\Tautulli\scripts\pythonw C:\Tautulli\Tautulli.py

Let me know if that works and I'll update the instructions.
Thanks for reporting.

**Comment by MrGarrettSmith** [comment]
> C:\Tautulli\scripts\pythonw C:\Tautulli\Tautulli.py

That seemed to work and let me launch Tautulli. Thank you!

And as for re-writing the installation instructions, I still have to use "py" or "python" to get the command to work instead of "python3" I'm not sure if its just my computer, so I would try it out and some other systems if you can. I would verify this myself on another computer, but I don't another one to try at the moment.

-------------------------------------------------------------------------------------------------------

By chance, would you happen to know how I could prevent a "PYTHONPATH" enviroment variable from interfering with launching Tautulli? I need the "PYTHONPATH" variable for another program to function. [I read this on the official FAQ, but I don't know what to do, or if I could use it.](https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#q-how-do-i-override-the-python-version-in-a-script)
