### ISSUE TITLE
Discord Notification

### ISSUE THREAD

**Issue by pellett655** [zSeriesGuy/Tautulli#29]
Trying to setup a Discord notification whenever any new media is added to Plex and am getting this error upon sending.

> 
>   | Tautulli NotificationHandler :: Notification thread exception: can't concat str to bytesTraceback (most recent call last):     File "C:\Tautulli\plexpy\notification_handler.py", line 55, in process_queue         notify(**params)     File "C:\Tautulli\plexpy\notification_handler.py", line 359, in notify         success = notifiers.send_notification(notifier_id=notifier_config['id'],     File "C:\Tautulli\plexpy\notifiers.py", line 641, in send_notification         return agent.notify(subject=subject,     File "C:\Tautulli\plexpy\notifiers.py", line 825, in notify         return self.agent_notify(subject=subject, body=body, action=action, **kwargs)     File "C:\Tautulli\plexpy\notifiers.py", line 1148, in agent_notify         text = subject.encode('utf-8') + '\r\n' + body.encode("utf-8") TypeError: can't concat str to bytes
> -- | --
> 

**Version:**
v4.0.07
**Operating system:**
Windows 10
**Python version:**
3.8

**Comment by zSeriesGuy** [comment]
Sorry about that. This is fallout from my conversion to Py3. I'm sure I missed a lot in the notifications area. I will try to get this fixed asap.

**Comment by zSeriesGuy** [comment]
Just pushed an update to master. Give it a try and let me know if that resolves it. Thanks.

**Comment by pellett655** [comment]
@zSeriesGuy yes! working! Appreciate all your efforts!

**Comment by zSeriesGuy** [comment]
Great!! Thanks for letting me know. If you have any other notifiers, please test them also. I only have an email notifier and can't really test anything else. I'm lazy and don't want to set up all those notifiers for testing. :)
