### ISSUE TITLE
How do you define the multiple servers?

### ISSUE THREAD

**Issue by ddurdle** [zSeriesGuy/Tautulli#3]
I see this supports it, but I cannot find where in the interface to define.

**Comment by zSeriesGuy** [comment]
@ddurdle You shouldn't have to define them. It will auto-discover all servers you own. If you are upgrading an existing Tautulli, you can go to the Settings->Plex Media Servers to edit the config for discovered servers.

**Comment by ddurdle** [comment]
All good now, thx.  

From you experience with doing the mod, do you think it would ever be possible for someone to add support for multiple plex accounts?
