### ISSUE TITLE
No Servers Defined

### ISSUE THREAD

**Issue by Tauli-gif** [zSeriesGuy/Tautulli#31]
**Version:**
Latest version on git as of 2020-03-25
**Branch:**
Tautulli V4.0.12
**Commit hash:**

**Operating system:**
Windows
**Python version:**
3.8.2
**What you did?**
logged in to my account
**What happened?**
No Servers Defined
**What are your (relevant) settings?**
Not sure what other settings to note here

**Comment by zSeriesGuy** [comment]
Please provide your log. See instructions here: https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support#how-can-i-share-my-logs

**Comment by zSeriesGuy** [comment]
I have tested with Python 3.8.0. I'll give it a shot with 3.8.2 to see if I can recreate.

**Comment by zSeriesGuy** [comment]
I tested with Python 3.8.2 and did not have any problems.
If you go into Tautulli Settings->Plex Media Servers, are your servers listed? Perhaps not enabled?

**Comment by Tauli-gif** [comment]
> If you go into Tautulli Settings->Plex Media Servers, are your servers listed? Perhaps not enabled?

No
![Tau 4](https://user-images.githubusercontent.com/57547419/78291965-96f3f980-7526-11ea-9d2e-78637085c036.JPG)
[tautulli.log](https://github.com/zSeriesGuy/Tautulli/files/4423154/tautulli.log)

**Comment by Tauli-gif** [comment]
I have now installed the version Tautulli-3.0.00 with Python 2.7.16. There both servers are shown to me but one with the IP 127.0.0.1 and it is supposedly offline.
[tautulli.log](https://github.com/zSeriesGuy/Tautulli/files/4423224/tautulli.log)

![Tau 3 1](https://user-images.githubusercontent.com/57547419/78293545-fd7a1700-7528-11ea-9f73-b7203248ec72.JPG)
![Tau 3 2](https://user-images.githubusercontent.com/57547419/78293547-fe12ad80-7528-11ea-97af-8fc07091c552.JPG)

**Comment by zSeriesGuy** [comment]
I am not supporting the V3.0.0 release anymore. Only reason that branch is still there is because of a pull request to the original Tautulli repo.

Looking at your first log from the V4 installation, I see some errors that I'll try to recreate and see what is going on.

**Comment by zSeriesGuy** [comment]
I have attempted to recreate what I thought might be the issue. But it worked fine for me.
I pushed a couple of small changes to my repo.
Could you download a fresh copy of the master branch and try it again? 
When you start Tautulli, please add -**-verbose** to the start command.
Send the log again from this test.

**Comment by Tauli-gif** [comment]
Thanks for the help, here the current log.

[tautulli.log](https://github.com/zSeriesGuy/Tautulli/files/4424030/tautulli.log)

**Comment by zSeriesGuy** [comment]
The log says No Plex Servers Found...which is weird since your test with V3.0.0 had found the two servers.
Are your servers claimed to the same user that you are logging into Tautulli with?
Do you see your servers when you log into plex web at https://app.plex.tv/desktop with that same user?
Have you defined anything different from defaults with the remote access on these servers such as the use of SSL, or custom URL, or anything else?

Try this from your browser: https://plex.tv/api/resources?X-Plex-Token=your-plex-token
Get your plex token from the bottom of the Plex Media Server tab of the Tautulli settings.
It should return an xml list of your devices which should include your servers.

But don't put that information here without cleaning it up since it contains some authentication information.

**Comment by Tauli-gif** [comment]
> Are your servers claimed to the same user that you are logging into Tautulli with?

Only one of the servers each server has its own user.

> Do you see your servers when you log into plex web at https://app.plex.tv/desktop with that same user?

Yes

> Have you defined anything different from defaults with the remote access on these servers such as the use of SSL, or custom URL, or anything else?

Secure connections only, nothing else.

![20200403_205731](https://user-images.githubusercontent.com/57547419/78395843-9030b980-75ee-11ea-8abe-2052d5dc99e0.jpg)
(Screenshot is from TV, I am not at home today.)

**Comment by Tauli-gif** [comment]
I have now reinstalled Tautulli-master and Python 3.8.2. Now my servers are found but I cannot activate the second server.

[tautulli.log](https://github.com/zSeriesGuy/Tautulli/files/4440570/tautulli.log)

![Opera Momentaufnahme_2020-04-06_220532_localhost](https://user-images.githubusercontent.com/57547419/78600297-fe75b600-7852-11ea-86ba-7407adcf36d7.png)
![Opera Momentaufnahme_2020-04-06_215717_localhost](https://user-images.githubusercontent.com/57547419/78600310-07ff1e00-7853-11ea-9a73-e1f8550eb5eb.png)

**Comment by zSeriesGuy** [comment]
Click on the gear to the right of that server in order to un-delete it.

**Comment by Tauli-gif** [comment]
I can't click anything on the server below. And I don't want to delete it either.

**Comment by zSeriesGuy** [comment]
There should be a gear to access the server's settings to the right of each server.
If you click on it, it will give you a message that will allow you to un-delete it.
Once it is un-deleted, you can then enable it.

**Comment by Tauli-gif** [comment]
Where?

![Plex](https://user-images.githubusercontent.com/57547419/78707997-b5386b80-7911-11ea-887d-a3f434c43e36.png)

**Comment by zSeriesGuy** [comment]
LOL...dang. I never tested that. The gear is being cut off on your screen resolution.
Try making the browser window a little smaller. It should then wrap the SERVERS box under the settings menu.
I'll see about fixing that box.
What resolution is your monitor?

**Comment by Tauli-gif** [comment]
Okay, now I see it. ^^ My default resolution is 1152x864.

**Comment by Tauli-gif** [comment]
I don't know what I'm doing wrong. When I login to Tautulli with the account from server one, sever one is active and server two is down. And when I log on to Tautulli with the account of server two, server two is active and server one is down. :(

![Opera Momentaufnahme_2020-04-07_220121_localhost](https://user-images.githubusercontent.com/57547419/78714130-9f2fa880-791b-11ea-8bf1-af818294c82e.png)
![Opera Momentaufnahme_2020-04-07_220216_localhost](https://user-images.githubusercontent.com/57547419/78714127-9dfe7b80-791b-11ea-9483-21cd929fb5f6.png)
![78293545-fd7a1700-7528-11ea-9f73-b7203248ec72](https://user-images.githubusercontent.com/57547419/78714639-8247a500-791c-11ea-813c-2a56f5f87fb5.jpg)

Sorry for my bad English.

**Comment by zSeriesGuy** [comment]
This version of Tautulli does not support multiple owners. It finds all servers OWNED by the userid that you sign into Tautulli with. So if the plex servers are owned by different plex login accounts, this won't work. 

Your english is very good. Much better than my Deutsche.

**Comment by Tauli-gif** [comment]
> This version of Tautulli does not support multiple owners. It finds all servers OWNED by the userid that you sign into Tautulli with. So if the plex servers are owned by different plex login accounts, this won't work.

Oh, all right, is that gonna be possible anytime soon?

> Your english is very good. Much better than my Deutsche.

Thanks :)

**Comment by zSeriesGuy** [comment]
Not likely. When I first wrote this version of Tautulli, my intent was to contribute to the original product. But they didn't accept my changes. 
Now that they are working on a Python 3 version, I may consider rewriting my code the correct way to contribute. 
This version is getting too far out of sync with the original.

**Comment by zSeriesGuy** [comment]
@Tauli-gif 
I just published a new branch (MultiAccounts) that will give you multiple Plex.TV account capability. 
**This is BETA code.** 
So be sure to back up you tautulli database and config before switching to this branch.

If you find any problems, please open a new issue here.
