### ISSUE TITLE
Custom Newsletter Templates Folder

### ISSUE THREAD

**Issue by Tchuch0** [zSeriesGuy/Tautulli#36]
Good morning,

 Version v4.1.00 is not saving the folder for the custom newsletter. Upon saving an error appears on the lower right corner.
 
 The same for 3rd party apis. It wont save cloudinary info por example.

Best regards,

**Comment by zSeriesGuy** [comment]
I'll look into this. Thanks for reporting it.

**Comment by Tchuch0** [comment]
Thanks for taking the time to check it @zSeriesGuy

**Comment by zSeriesGuy** [comment]
The fix for the other issue should also resolve this one.

**Comment by Tchuch0** [comment]
Correct @zSeriesGuy. i can now save the option for cloudinary for example. Tried to load my tautulli custom html but got an error. Do the newsletter have any different parameters?

Best regards,

**Comment by zSeriesGuy** [comment]
There are some changes in my version of Tautulli newsletter template related to server_id for the multi-server support. I wonder if there is an easy way to compare the original to mine to see the differences.

**Comment by Tchuch0** [comment]
It's always the same 2 or 3 things that all the users wanna change so i did it from scratch using this fork's base model. Name and Logo and all done.

From my end this issue is fixed with the new update :-)
