### ISSUE TITLE
Best way to update?

### ISSUE THREAD

**Issue by Tchuch0** [zSeriesGuy/Tautulli#39]
Hi,

 got the notification of a new release but upon "updating" the reboot wont get to the latest version.

Any tips ?

Thanks in advance

**Comment by zSeriesGuy** [comment]
If you are doing the upgrade through Tautulli dashboard, you might check to make sure all files are owned by the userid that you are running Tautulli under.
Also, check your Tautulli log to see if there are any errors.

**Comment by Tchuch0** [comment]
i was via the dashboard but the update was being applied but still receiving the notification about an update. I copied the source via ftp and same thing, still getting the "warning" about the update but i've checked the version and it is the latested.

**Comment by zSeriesGuy** [comment]
Any messages in the log?
If you like, you can send me your log. The instructions are in the **How to Share My Log** section of [https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support
)

**Comment by Tchuch0** [comment]
Hi,

 sorry for the late reply.

no msg on logs. 

will be sharing them with you next

**Comment by Tchuch0** [comment]
Good morning,

 fresh install, backup applied and all working. maybe i messed up something on the first install.
![1](https://user-images.githubusercontent.com/68711301/94987186-33419c00-055c-11eb-90bc-89af9517a4a0.PNG)
