### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Tchuch0** [zSeriesGuy/Tautulli#41]
Good morning,

 since the first version from time to time i get a "time out" on the page that forces to do a refresh. 

Is this something i can change in the settings? I have this setup on a vm with centOS in case it can be related.

Thanks in advance
![net](https://user-images.githubusercontent.com/68711301/94988838-0d21f900-0568-11eb-8f8d-8507124ef0d4.PNG)

**Comment by zSeriesGuy** [comment]
Try adjusting the pms_timeout in your config.ini.
I don't believe there is any way to adjust that through the Tautulli webpage. You have to just edit it directly.
I think you will also need to restart Tautulli after making the change.
There is also a websocket_connection_timeout setting in config.ini. But I think the pms_timeout is the one to change.

**Comment by Tchuch0** [comment]
Hi,

 testing it now.

Thanks for the quick reply

**Comment by Tchuch0** [comment]
Good morning,

 it is fixed @zSeriesGuy.

Thanks again for the help :-)

**Comment by zSeriesGuy** [comment]
Glad to hear that resolved it for you.
