### ISSUE TITLE
not able to set a manuel connection to server

### ISSUE THREAD

**Issue by moooep** [zSeriesGuy/Tautulli#42]
i am not able to set a manual connection to add a server on another server on the same network.
it even doesnt change on the overview after exiting server settings.

looking forward to use your great fork.

**Comment by zSeriesGuy** [comment]
Hi moooep. It should auto discover any plex servers that are owned by the plex account that you signed into tautulli with or defined in the plex.tv accounts setting.
What is your configuration? Tautulli and two plex servers on the same local network? Are both plex servers owned by the same account? Are they using the same remote port? If they have the same remote port, try changing it on one of them in the plex server settings.

**Comment by moooep** [comment]
hi, thanks for replaying that fast. 

i am using docker for plex so my plex servers are connected to a virtual network. tautulli detects the IP like 17.0.18.X:32400 (docker network only local on the machine reachable) but i want to change it manually to 192.168.0.X:32404 so i can access from another server on the network. and no - they are not owned by the same account actually and use different ports.

**Comment by zSeriesGuy** [comment]
Since the server is owned by a different plex account, go to the plex.tv account setting in tautulli and add the other account. It should then discover the other server

**Comment by moooep** [comment]
i guess you don’t get me right. even the first server isn’t discovered properly. because it’s detected on the wrong network.

**Comment by zSeriesGuy** [comment]
Sorry about that.
I'm not familiar with docker.
Is your tautulli in the same docker container or a different server, different subnet?

If tautulli detected the plex server on that docker network, can you not just leave the address? If that network is only a local to the docker container network, I'm wondering how tautulli detected it. Are you able to access the plex server from the app.plex.tv web interface? Again, might be my lack of understanding of docker.

When I wrote this fork, I removed the ability to manually edit the plex server IP address. Might have been a bad decision on my part perhaps. But my thought was to let tautulli discover the servers through your plex.tv account. So I would think that if you can access them through the plex web interface, tautulli should be able to access it....I would think.

All that said, I just reread your last post about it detecting on the wrong network. Hummm...going to have to think about that one. It is a scenario I did not consider in development.

**Comment by zSeriesGuy** [comment]
Again, not being familier with docker, I'm assuming the docker container has two network interfaces, one being the private virtual network and the other being the 192.168.0.* network.
In the Plex server network settings, there is a "preferred network interface" setting. If you set that to the 192 network interface, I wonder if that might work.

**Comment by zSeriesGuy** [comment]
Any luck with it?

**Comment by moooep** [comment]
sorry for my late response. i was busy on other things. i was successful connecting the server using a docker overlay network. but i am running in this error right now which causes i cannot monitor the server: 
```Uncaught exception: Traceback (most recent call last):
    File "/app/plexpy/logger.py", line 341, in new_run 
        old_run(*args, **kwargs) 
    File "/usr/local/lib/python3.10/threading.py", line 946, in run 
        self._target(*self._args, **self._kwargs) 
    File "/app/plexpy/servers.py", line 375, in refresh 
        self.start() 
    File "/app/plexpy/servers.py", line 291, in start 
        self.WS.start() 
    File "/app/plexpy/web_socket.py", line 55, in start 
        if not self.WS_THREAD.isAlive(): 
AttributeError: 'ServerWebSocketThread' object has no attribute 'isAlive' ```

**Comment by zSeriesGuy** [comment]
Looks like you might be using Python 3.10. I have not tested with 3.10 yet. I suspect there is some kind of incompatibility that I will need to address. In the meantime, can you try with Python 3.9?

**Comment by zSeriesGuy** [comment]
thread.isAlive() had been deprecated and finally removed. 
I'll be pushing out an update shortly to fix this.

**Comment by zSeriesGuy** [comment]
V4.1.07 has been uploaded. It should resolve the issue with py 3.10.

**Comment by zSeriesGuy** [comment]
Is this issue resolved?
