### ISSUE TITLE
Script Problem

### ISSUE THREAD

**Issue by Tchuch0** [zSeriesGuy/Tautulli#43]
Was going for kill_stream script but got a few errors although i got python 3 installed...

root@localhost Scripts]# python kill_stream.py --jbop stream --username {username} --sessionId {session_id} --killMessage 'Transcoding streams are not allowed.'
Traceback (most recent call last):
  File "kill_stream.py", line 572, in <module>
    opts = parser.parse_args()
  File "/usr/lib64/python3.6/argparse.py", line 1734, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.6/argparse.py", line 2265, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib64/python3.6/argparse.py", line 2294, in _get_value
    result = type_func(arg_string)
  File "kill_stream.py", line 95, in arg_decoding
    return arg.decode(TAUTULLI_ENCODING).encode('UTF-8')
AttributeError: 'str' object has no attribute 'decode'

Just wondering if anyone got it working with this awesome branch of Tautulli

**Comment by zSeriesGuy** [comment]
Are you using the official kill_stream from the official Tautulli? If so, take a look at this issue:
[https://github.com/zSeriesGuy/Tautulli/issues/27](https://github.com/zSeriesGuy/Tautulli/issues/27)

**Comment by zSeriesGuy** [comment]
Did this work for you?

**Comment by Tchuch0** [comment]
Good morning @zSeriesGuy , it caused me another weird problem. I could not login, neither with plex username or the admin username... i'll take this weekend to start fresh on a new vm since i really really want the multi server feature :-)

 Will report after.


Best regards

**Comment by zSeriesGuy** [comment]
That's odd. I don't understand how it would cause a login problem. 
Is all you did was download my copy of kill_stream? You should not have had to change anything else.
[Kill_Stream](https://github.com/zSeriesGuy/Tautulli/files/4277790/kill_stream.zip)

**Comment by zSeriesGuy** [comment]
Is this issue resolved?

**Comment by Tchuch0** [comment]
Hi Jerry, new install on a new vm all good. something messed it up on the login screen and i could not get around it.

thanks for the help :-)
