### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by morganzero** [zSeriesGuy/Tautulli#44]
Hi, Thank you for your work. Do you plan on dockerizing this solution?

**Comment by zSeriesGuy** [comment]
No. I don't really know much about docker. But some others have forked this fork and dockerized it.
See this one. [https://github.com/timekills/multitautulli](https://github.com/timekills/multitautulli)

**Comment by barocko-works** [comment]
Thanks alot. I'll have a look. His repo doesn't seem to be up to date though.

Best,
Morgan
