### ISSUE TITLE
Tautulli update

### ISSUE THREAD

**Issue by morganzero** [zSeriesGuy/Tautulli#45]
Hi, how does it work to update Tautulli, will your mod still work? And also, will you update soon too?

**Comment by zSeriesGuy** [comment]
Updates should work very similar to the official Tautulli. If you click on the gear in upper right and check for updates, it should tell you if there are any.
I have not updated this fork in a long time. I'm still using it for my Plex servers. But I don't have any planned updates at this time.

**Comment by barocko-works** [comment]
Thanks for the reply. I'm creating my dockerized version of your fork. However, I plan to make one that fetches the latest original Tautulli version which then applies your modifications on top instead. Would you please let me know which files you have precisely modified? That would help!

**Comment by zSeriesGuy** [comment]
My modifications were rather massive and changed almost every modules in the original Tautulli, about 9000 lines of code changes. I doubt you would be able to overlay my changes on to the original Tautulli.
