### ISSUE TITLE
Request for official Docker image

### ISSUE THREAD

**Issue by ghost** [zSeriesGuy/Tautulli#8]
Can you create an official Docker image for your fork of Tautulli and push it to the Docker Hub?

**Comment by ebadenes** [comment]
I did it for my this weekend.
I just loaded it now on github, if you want to try [Docker-tautulli-multi-server](https://github.com/ebadenes/Docker-tautulli-multi-server)

**Comment by ghost** [comment]
@ebadenes Thank you kindly!

**Comment by zSeriesGuy** [comment]
@ebadenes Thanks a bunch. I know nothing about Docker and would not have been able to accomplish this.
